# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # deps
  - package-ecosystem: nuget
    target-branch: 'master'
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
    directory: /
    commit-message:
      prefix: 'deps'

  # github deps
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: 'ci'
    directory: '/'
