name: format_check

on:
  workflow_call:

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Install JetBrains ReSharper Global Tools (jb)
        shell: bash
        run: |
          set -euo pipefail
          cd /tmp
          dotnet tool install --global JetBrains.ReSharper.GlobalTools
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Discover all solutions
        id: discover
        shell: bash
        run: |
          set -euo pipefail
          git ls-files '*.sln' > solutions.txt || true
          echo "Found solution files:"
          cat solutions.txt || true
          count=$(wc -l < solutions.txt | tr -d ' ')
          echo "solution_count=$count" >> "$GITHUB_OUTPUT"

      - name: Check formatting
        if: steps.discover.outputs.solution_count != '0'
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r sln; do
            [ -z "$sln" ] && continue
            echo "==> Restoring $sln"
            dotnet restore "$sln"

            echo "==> Running jb cleanupcode"
            jb cleanupcode "$sln" \
              --profile="Built-in: Reformat Code" \
              --no-build \
              --verbosity=WARN \
              --include="Assets/**/*.cs" \
              --exclude="**/bin/**" \
              --exclude="**/obj/**" \
              --exclude="**/.idea/**" \
              --exclude="**/Library/**" \
              --exclude="**/Logs/**" \
              --exclude="**/Temp/**"
          done < solutions.txt

      - name: Diff & annotate unformatted files (fail if any)
        if: steps.discover.outputs.solution_count != '0'
        shell: bash
        run: |
          set -euo pipefail
          DIFF_FILE=cleanup.diff
          git --no-pager diff --unified=0 -- 'Assets/**/*.cs' > "$DIFF_FILE" || true

          if [ -s "$DIFF_FILE" ]; then
            echo "Unformatted changes detected in Assets/:"
            awk '
              BEGIN { file="" }
              /^\+\+\+ b\// { sub(/^\+\+\+ b\//, "", $0); file=$0; next }
              /^@@ / {
                match($0, /\+([0-9]+)(,([0-9]+))?/, m)
                start = m[1]
                printf("::error file=%s,line=%d,title=Formatting differs::Run Rider Code Cleanup (or jb cleanupcode) locally and commit.\n", file, start)
              }
            ' "$DIFF_FILE"
            echo "::error title=Formatting check failed::Some files under Assets/ differ from the configured formatting."
            exit 1
          else
            echo "Formatting is clean in Assets/."
          fi

      - name: No solutions found (informative)
        if: steps.discover.outputs.solution_count == '0'
        run: echo "No .sln files found; skipping formatting check."
